config/routes.rb
OycApp::Application.routes.draw do
  resources :titles
  resources :stockaudititems
  resources :bookfairs do
    get 'active', :on => :collection
  end
  resources :billitems
  resources :bills
  resources :invoices do
    get 'fetch_suppliers', :on => :collection
  end
  resources :titlereceipts
  
  match 'titles/fetch_by_isbn/:isbn' => 'titles#fetch_by_isbn'
  match 'invoices/fetch_invoices_for_supplier/:supplier_id' => 'invoices#fetch_invoices_for_supplier'

  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  match '/auth/failure' => 'Dashboard#show'
  resources :authentications, :branches

  root :to => "Dashboard#show"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    if params[:current_branch].blank?
      user_session['current_branch'] = Branch.branch_from_subdomain(current_user.subdomain)
    else
      user_session['current_branch'] = Branch.find(params[:current_branch].to_i)
    end
    @associate_branches = Branch.associate_branches(current_user.subdomain)
  end
end

app/views/dashboard/show.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

<!--
<div class='notice'>
	You are a staff of <b><%= Branch.branch_name_from_subdomain(current_user.subdomain) %>.</b>
	If this is not correct, call tech support.
	<br/>
	You are currently logged into <%= user_session['current_branch'].name %>. 
	<% if  @associate_branches.length > 1 -%>
		<hr/>
		Click on any of the following branches to change your current branch.
		<br/>
		<ol>
			<% @associate_branches.each do |b| -%>
				<li><%= link_to b.name, dashboard_path(:current_branch => b.id), :confirm => "Are you sure you want to change the branch to #{b.name}?" %></li>
			<% end -%>
		</ol>
	<% end -%>		
</div>
-->

<div id='left-nav' style="width:10%">
  <div><%= link_to "Invoices", invoices_path %></div>
  <div><%= link_to "Titlereceipts", titlereceipts_path %></div>
  <div><%= link_to "Bills", bills_path %></div>
  <div><%= link_to "Bill Items", billitems_path %></div>
  <div><%= link_to "Book Fairs", bookfairs_path %></div>
</div>
<div id='center' style="width:90%">
</div>

<% if current_user.frontoffice? -%>
  <div class='alert'>
	  You logged in with <%= current_user.email %>, instead use the id that was created for you.
  </div>
<% end -%>