config/routes.rb
OycApp::Application.routes.draw do
  resources :titles
  resources :stockaudititems
  resources :bookfairs do
    get 'active', :on => :collection
  end
  resources :billitems
  resources :bills
  resources :invoices do
    get 'fetch_suppliers', :on => :collection
  end
  resources :titlereceipts
  
  match 'titles/fetch_by_isbn/:isbn' => 'titles#fetch_by_isbn'
  match 'invoices/fetch_invoices_for_supplier/:supplier_id' => 'invoices#fetch_invoices_for_supplier'

  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  match '/auth/failure' => 'Dashboard#show'
  resources :authentications, :branches

  root :to => "Dashboard#show"

end

app/models/invoice.rb
# == Schema Information
# Schema version: 20110427172104
#
# Table name: invoices
#
#  id              :integer(38)     not null, primary key
#  invoice_no      :string(255)     not null
#  date_of_invoice :datetime
#  isbn            :string(255)     not null
#  title           :string(255)     not null
#  publisher       :string(255)     not null
#  author          :string(255)
#  quantity        :integer(38)     not null
#  grossamt        :decimal(, )     not null
#  currency        :string(255)
#  conv_rate       :decimal(, )
#  discount        :decimal(, )
#  netamt          :decimal(, )
#  received_cnt    :integer(38)     default(0)
#  created_by      :integer(38)
#  updated_by      :integer(38)
#  created_at      :datetime
#  updated_at      :datetime
#  supplier_id     :integer(38)
#

class Invoice < ActiveRecord::Base
  belongs_to  :supplier
  has_many    :titlereceipts
  has_many    :titles
  
  before_create :make_uppercase
  
  scope :distinct_suppliers, :select => "DISTINCT supplier_id"  
  scope :of_supplier, lambda { |supplier_id|
      where(:supplier_id => supplier_id)
    }
  scope :distinct_invoices, :select => "DISTINCT invoice_no"
  
  private 
    def make_uppercase
      self.invoice_no = self.invoice_no.upcase
    end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  # GET /invoices
  # GET /invoices.xml
  def index
    @invoices = Invoice.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @invoices }
    end
  end

  # GET /invoices/1
  # GET /invoices/1.xml
  def show
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  # GET /invoices/new
  # GET /invoices/new.xml
  def new
    @invoice = Invoice.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @invoice }
    end
  end

  # GET /invoices/1/edit
  def edit
    @invoice = Invoice.find(params[:id])
  end

  # POST /invoices
  # POST /invoices.xml
  def create
    @invoice = Invoice.new(params[:invoice])

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully created.') }
        format.xml  { render :xml => @invoice, :status => :created, :location => @invoice }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /invoices/1
  # PUT /invoices/1.xml
  def update
    @invoice = Invoice.find(params[:id])

    respond_to do |format|
      if @invoice.update_attributes(params[:invoice])
        format.html { redirect_to(@invoice, :notice => 'Invoice was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @invoice.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.xml
  def destroy
    @invoice = Invoice.find(params[:id])
    @invoice.destroy

    respond_to do |format|
      format.html { redirect_to(invoices_url) }
      format.xml  { head :ok }
    end
  end
  
  def fetch_suppliers
    @suppliers = Supplier.in_invoices
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml
    end
  end
  
  def fetch_invoices_for_supplier
    @invoices = Invoice.of_supplier(params[:supplier_id]).distinct_invoices
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml
    end
  end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>

      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :invoice_no %><br />
    <%= f.text_field :invoice_no %>
  </div>
  <div class="field">
    <%= f.label :date_of_invoice %><br />
    <%= f.date_select :date_of_invoice %>
  </div>
  <div class="field">
    <%= f.label :isbn %><br />
    <%= f.text_field :isbn %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publisher %><br />
    <%= f.text_field :publisher %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.text_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :grossamt %><br />
    <%= f.text_field :grossamt %>
  </div>
  <div class="field">
    <%= f.label :currency %><br />
    <%= f.text_field :currency %>
  </div>
  <div class="field">
    <%= f.label :conv_rate %><br />
    <%= f.text_field :conv_rate %>
  </div>
  <div class="field">
    <%= f.label :discount %><br />
    <%= f.text_field :discount %>
  </div>
  <div class="field">
    <%= f.label :netamt %><br />
    <%= f.text_field :netamt %>
  </div>
  <div class="field">
    <%= f.label :received_cnt %><br />
    <%= f.text_field :received_cnt %>
  </div>
  <div class="field">
    <%= f.label :sold_cnt %><br />
    <%= f.text_field :sold_cnt %>
  </div>
  <div class="field">
    <%= f.label :created_by %><br />
    <%= f.text_field :created_by %>
  </div>
  <div class="field">
    <%= f.label :updated_by %><br />
    <%= f.text_field :updated_by %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/fetch_invoices_for_supplier.xml.erb
<invoices>
  <% @invoices.each do |invoice| %>
    <invoice>
      <invoice_no><%= invoice.invoice_no %></invoice_no>
    </invoice>
  <% end %>
</invoices>

app/views/invoices/fetch_suppliers.xml.erb
<suppliers>
  <% @suppliers.each do |supplier| %>
    <supplier>
      <id><%= supplier.id %></id>
      <name><%= supplier.name %></name>
    </supplier>
  <% end %>
</suppliers>

app/views/invoices/index.html.erb
<h1>Listing invoices</h1>

<table>
  <tr>
    <th>Invoice no</th>
    <th>Date of invoice</th>
    <th>Isbn</th>
    <th>Title</th>
    <th>Publisher</th>
    <th>Author</th>
    <th>Quantity</th>
    <th>Grossamt</th>
    <th>Currency</th>
    <th>Conv rate</th>
    <th>Discount</th>
    <th>Netamt</th>
    <th>Received cnt</th>
    <th>Created by</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @invoices.each do |invoice| %>
  <tr>
    <td><%= invoice.invoice_no %></td>
    <td><%= invoice.date_of_invoice %></td>
    <td><%= invoice.isbn %></td>
    <td><%= invoice.title %></td>
    <td><%= invoice.publisher %></td>
    <td><%= invoice.author %></td>
    <td><%= invoice.quantity %></td>
    <td><%= invoice.grossamt %></td>
    <td><%= invoice.currency %></td>
    <td><%= invoice.conv_rate %></td>
    <td><%= invoice.discount %></td>
    <td><%= invoice.netamt %></td>
    <td><%= invoice.received_cnt %></td>
    <td><%= invoice.created_by %></td>
    <td><%= invoice.updated_by %></td>
    <td><%= link_to 'Show', invoice %></td>
    <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
    <td><%= link_to 'Destroy', invoice, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Invoice no:</b>
  <%= @invoice.invoice_no %>
</p>

<p>
  <b>Date of invoice:</b>
  <%= @invoice.date_of_invoice %>
</p>

<p>
  <b>Isbn:</b>
  <%= @invoice.isbn %>
</p>

<p>
  <b>Title:</b>
  <%= @invoice.title %>
</p>

<p>
  <b>Publisher:</b>
  <%= @invoice.publisher %>
</p>

<p>
  <b>Author:</b>
  <%= @invoice.author %>
</p>

<p>
  <b>Quantity:</b>
  <%= @invoice.quantity %>
</p>

<p>
  <b>Grossamt:</b>
  <%= @invoice.grossamt %>
</p>

<p>
  <b>Currency:</b>
  <%= @invoice.currency %>
</p>

<p>
  <b>Conv rate:</b>
  <%= @invoice.conv_rate %>
</p>

<p>
  <b>Discount:</b>
  <%= @invoice.discount %>
</p>

<p>
  <b>Netamt:</b>
  <%= @invoice.netamt %>
</p>

<p>
  <b>Received cnt:</b>
  <%= @invoice.received_cnt %>
</p>

<p>
  <b>Sold cnt:</b>
  <%= @invoice.sold_cnt %>
</p>

<p>
  <b>Created by:</b>
  <%= @invoice.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%= @invoice.updated_by %>
</p>


<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>