config/routes.rb
OycApp::Application.routes.draw do
  resources :titles
  resources :stockaudititems
  resources :bookfairs do
    get 'active', :on => :collection
  end
  resources :billitems
  resources :bills
  resources :invoices do
    get 'fetch_suppliers', :on => :collection
  end
  resources :titlereceipts
  
  match 'titles/fetch_by_isbn/:isbn' => 'titles#fetch_by_isbn'
  match 'invoices/fetch_invoices_for_supplier/:supplier_id' => 'invoices#fetch_invoices_for_supplier'

  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  match '/auth/failure' => 'Dashboard#show'
  resources :authentications, :branches

  root :to => "Dashboard#show"

end

app/models/bookfair.rb
# == Schema Information
# Schema version: 20110426120952
#
# Table name: bookfairs
#
#  id         :integer(38)     not null, primary key
#  name       :string(255)
#  start_date :datetime
#  end_date   :datetime
#  created_by :integer(38)
#  updated_by :integer(38)
#  created_at :datetime
#  updated_at :datetime
#  active     :string(255)
#

class Bookfair < ActiveRecord::Base
  has_many :bills
  
  scope :active, where(:active => 'Y')
  
  before_save :set_defaults
  
  private
    def set_defaults
      self.active = 'Y'
    end
end

app/controllers/bookfairs_controller.rb
class BookfairsController < ApplicationController
  # GET /bookfairs
  # GET /bookfairs.xml
  def index
    @bookfairs = Bookfair.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bookfairs }
    end
  end

  # GET /bookfairs/1
  # GET /bookfairs/1.xml
  def show
    @bookfair = Bookfair.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bookfair }
    end
  end

  # GET /bookfairs/new
  # GET /bookfairs/new.xml
  def new
    @bookfair = Bookfair.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bookfair }
    end
  end

  # GET /bookfairs/1/edit
  def edit
    @bookfair = Bookfair.find(params[:id])
  end

  # POST /bookfairs
  # POST /bookfairs.xml
  def create
    @bookfair = Bookfair.new(params[:bookfair])

    respond_to do |format|
      if @bookfair.save
        format.html { redirect_to(@bookfair, :notice => 'Bookfair was successfully created.') }
        format.xml  { render :xml => @bookfair, :status => :created, :location => @bookfair }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bookfair.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bookfairs/1
  # PUT /bookfairs/1.xml
  def update
    @bookfair = Bookfair.find(params[:id])

    respond_to do |format|
      if @bookfair.update_attributes(params[:bookfair])
        format.html { redirect_to(@bookfair, :notice => 'Bookfair was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bookfair.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bookfairs/1
  # DELETE /bookfairs/1.xml
  def destroy
    @bookfair = Bookfair.find(params[:id])
    @bookfair.destroy

    respond_to do |format|
      format.html { redirect_to(bookfairs_url) }
      format.xml  { head :ok }
    end
  end
  
  def active
    @bookfairs = Bookfair.active

    respond_to do |format|
      format.html # index.html.erb
      format.xml
    end
  end
end

app/helpers/bookfairs_helper.rb
module BookfairsHelper
end

app/views/bookfairs/_form.html.erb
<%= form_for(@bookfair) do |f| %>
  <% if @bookfair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bookfair.errors.count, "error") %> prohibited this bookfair from being saved:</h2>

      <ul>
      <% @bookfair.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.date_select :start_date, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
    <%= f.label :end_date %><br />
    <%= f.date_select :end_date, :order => [:day, :month, :year] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookfairs/active.xml.erb
<bookfairs>
  <% @bookfairs.each do |bookfair| %>
    <bookfair>
      <id><%= bookfair.id %></id>
      <name><%= bookfair.name %></name>
    </bookfair>
  <% end %>
</bookfairs>

app/views/bookfairs/edit.html.erb
<h1>Editing bookfair</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookfair %> |
<%= link_to 'Back', bookfairs_path %>

app/views/bookfairs/index.html.erb
<h1>Listing bookfairs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Start date</th>
    <th>End date</th>
    <th>Created by</th>
    <th>Updated by</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookfairs.each do |bookfair| %>
  <tr>
    <td><%= bookfair.name %></td>
    <td><%= bookfair.start_date %></td>
    <td><%= bookfair.end_date %></td>
    <td><%= bookfair.created_by %></td>
    <td><%= bookfair.updated_by %></td>
    <td><%= link_to 'Show', bookfair %></td>
    <td><%= link_to 'Edit', edit_bookfair_path(bookfair) %></td>
    <td><%= link_to 'Destroy', bookfair, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bookfair', new_bookfair_path %>

app/views/bookfairs/new.html.erb
<h1>New bookfair</h1>

<%= render 'form' %>

<%= link_to 'Back', bookfairs_path %>

app/views/bookfairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bookfair.name %>
</p>

<p>
  <b>Start date:</b>
  <%= @bookfair.start_date %>
</p>

<p>
  <b>End date:</b>
  <%= @bookfair.end_date %>
</p>

<p>
  <b>Created by:</b>
  <%= @bookfair.created_by %>
</p>

<p>
  <b>Updated by:</b>
  <%= @bookfair.updated_by %>
</p>


<%= link_to 'Edit', edit_bookfair_path(@bookfair) %> |
<%= link_to 'Back', bookfairs_path %>