config/routes.rb
OycApp::Application.routes.draw do
  resources :titles
  resources :stockaudititems
  resources :bookfairs do
    get 'active', :on => :collection
  end
  resources :billitems
  resources :bills
  resources :invoices do
    get 'fetch_suppliers', :on => :collection
  end
  resources :titlereceipts
  
  match 'titles/fetch_by_isbn/:isbn' => 'titles#fetch_by_isbn'
  match 'invoices/fetch_invoices_for_supplier/:supplier_id' => 'invoices#fetch_invoices_for_supplier'

  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}

  match '/auth/failure' => 'Dashboard#show'
  resources :authentications, :branches

  root :to => "Dashboard#show"

end

app/models/bill.rb
# == Schema Information
# Schema version: 20110525064617
#
# Table name: bills
#
#  id              :integer(38)     not null, primary key
#  date_of_billing :datetime
#  created_at      :datetime
#  updated_at      :datetime
#  created_by      :integer(38)
#  updated_by      :integer(38)
#  bookfair_id     :integer(38)     not null
#  grossamt        :decimal(, )
#  quantity        :integer(38)
#  netamt          :decimal(, )
#

class Bill < ActiveRecord::Base
  belongs_to  :bookfair
  
  has_many    :billitems, :dependent => :destroy
  accepts_nested_attributes_for :billitems, :allow_destroy => :true, :reject_if => lambda { |a| a[:isbn].blank? }
  
  validates :bookfair_id,             :presence => true

  before_create                       :set_defaults
  
  private
    def set_defaults
      if date_of_billing.blank?
        self.date_of_billing = Time.now
      end
      if self.quantity.blank?
		    self.quantity = 0
		    self.grossamt = 0.0
		    self.netamt = 0.0
	    end      
    end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  # GET /bills
  # GET /bills.xml
  def index
    @bills = Bill.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bills }
    end
  end

  # GET /bills/1
  # GET /bills/1.xml
  def show
    @bill = Bill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/new
  # GET /bills/new.xml
  def new
    @bill = Bill.new
    5.times { @bill.billitems.build }

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # GET /bills/1/edit
  def edit
    @bill = Bill.find(params[:id])
    5.times { @bill.billitems.build }
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bill }
    end
  end

  # POST /bills
  # POST /bills.xml
  def create
    @bill = Bill.new(params[:bill])

    respond_to do |format|
      if @bill.save
        format.html { redirect_to(@bill, :notice => 'Bill was successfully created.') }
        format.xml
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bills/1
  # PUT /bills/1.xml
  def update
    @bill = Bill.find(params[:id])
    
    respond_to do |format|
      if @bill.update_attributes(params[:bill])
        format.html { redirect_to(@bill, :notice => 'Bill was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bill.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.xml
  def destroy
    @bill = Bill.find(params[:id])
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to(bills_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_billitem_fields.html.erb
<tr>
	<td><%= f.text_field :isbn %></td>
	<td><%= f.text_field :discount %></td>
</tr>

app/views/bills/_form.html.erb
<%= form_for(@bill) do |f| %>
  <% if @bill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bill.errors.count, "error") %> prohibited this bill from being saved:</h2>

      <ul>
      <% @bill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_billing %><br />
    <%= f.date_select :date_of_billing %>
  </div>
  <div class="field">
    <%= f.label :bookfair_id %><br />
    <%= f.text_field :bookfair_id %>
  </div>
  
	<table id='billitems_table' style="width:20%">
		<tr><th>ISBN</th></tr>
		<%= f.fields_for :billitems do |builder| -%>
			<%= render 'billitem_fields', :f => builder %>
		<% end -%>
	</table>
		
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bills/create.xml.erb
<bill>
  <bill_no><%= @bill.id %></bill_no>
</bill>

app/views/bills/edit.html.erb
<h1>Editing bill</h1>

<%= render 'form' %>

<%= link_to 'Show', @bill %> |
<%= link_to 'Back', bills_path %>

app/views/bills/index.html.erb
<h1>Listing bills</h1>

<table>
  <tr>
    <th>Date of billing</th>
    <th>Amount</th>
    <th>Quantity</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bills.each do |bill| %>
  <tr>
    <td><%= bill.date_of_billing %></td>
    <td><%= bill.grossamt %></td>
    <td><%= bill.quantity %></td>
    <td><%= bill.netamt %></td>
    <td><%= link_to 'Show', bill %></td>
    <td><%= link_to 'Edit', edit_bill_path(bill) %></td>
    <td><%= link_to 'Destroy', bill, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bill', new_bill_path %>

app/views/bills/new.html.erb
<h1>New bill</h1>

<%= render 'form' %>

<%= link_to 'Back', bills_path %>

app/views/bills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date of billing:</b>
  <%= @bill.date_of_billing %>
</p>

<p>
  <b>Gross Amount:</b>
  <%= @bill.grossamt %>
</p>

<p>
  <b>Net Amount:</b>
  <%= @bill.netamt %>
</p>

<p>
  <b>Quantity:</b>
  <%= @bill.quantity %>
</p>


<%= link_to 'Edit', edit_bill_path(@bill) %> |
<%= link_to 'Back', bills_path %>